name: Android Build (macOS 15 ARM64 + Preinstall NDK)

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - 'Documents/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'Documents/**'
  release:
    types: [published]
    paths-ignore:
      - '*.md'
      - 'Documents/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Install NDK 23.2.8568313
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;23.2.8568313"

      - name: Download SDL2 source
        run: |
          SDL_VERSION=2.32.8
          curl -LO https://github.com/libsdl-org/SDL/releases/download/release-$SDL_VERSION/SDL2-$SDL_VERSION.zip
          unzip SDL2-$SDL_VERSION.zip
          mkdir -p Builder/Android/app/jni/SDL
          cp -r SDL2-$SDL_VERSION/include Builder/Android/app/jni/SDL/
          cp -r SDL2-$SDL_VERSION/src Builder/Android/app/jni/SDL/
          mkdir -p Builder/Android/app/src/java/org/libsdl
          cp -r SDL2-$SDL_VERSION/android-project/app/src/main/java/org/libsdl/app \
             Builder/Android/app/src/java/org/libsdl/

      - name: Build with Gradle
        working-directory: Builder/Android
        run: |
          # 今回は、Secrets が設定されいなければ署名なしのapkファイルが作成されるよう判定処理をいれています。
          # 確実に署名させたいのであれば、判定処理を外すことで署名エラーとしてしまってもよいと思います。
          if [[ -n "${{ secrets.KEYSTORE_BASE64 }}" ]]; then
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore
            export KEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}"
            export KEY_ALIAS="${{ secrets.KEY_ALIAS }}"
            export KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
          fi
          ./gradlew assembleRelease

      # - name: Build Release APK
      #   working-directory: Builder/Android
      #   run: ./gradlew assembleRelease --no-daemon -PKEYSTORE_FILE=app/keystore.jks -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} -PKEY_ALIAS=${{ secrets.KEY_ALIAS }} -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }}

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: XM8_Android_APKs
          path: |
            Builder/Android/app/build/outputs/apk/release/*.apk